site_name: Iden3 documentation

site_url: https://iden3.io/
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep purple
  logo: logo-white.svg
  # favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
    - content.code.copy
markdown_extensions:
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.superfences
  - fenced_code
  - tables

nav:
  - Home: "index.md"
  - W3C credential:
    - Refresh service: "w3c/refresh-service/overview.md"
    - Credential Statuses: "w3c/status/overview.md"
    - Display method: "w3c/display-method/overview.md"
    - Proofs:
        - BJJSignature2021: "w3c/proofs/bjj.md"
        - Iden3SparseMerkleTreeProof: "w3c/proofs/smt.md"
  - Protocol:
    - Media-types: "media-types/overview.md"
    - Credentials:
        - Overview: "credentials/overview.md"
        - Messages (1.0):
          - Issuance Request: "credentials/1.0/issuance-request.md"
          - Issuance Response: "credentials/1.0/issuance-response.md"
          - Fetch Request: "credentials/1.0/fetch-request.md"
          - Offer: "credentials/1.0/offer.md"
          - Status update: "credentials/1.0/status-update.md"
          - Refresh: "credentials/1.0/refresh.md"
          - Onchain-offer: "credentials/1.0/onchain-offer.md"
        - Beta (0.1):
          - Payment Request: "credentials/0.1/payment-request.md"
          - Payment : "credentials/0.1/payment.md"
          - Proposal Request: "credentials/0.1/proposal-request.md"
          - Proposal: "credentials/0.1/proposal.md"
    - Authorization:
        - Overview: "authorization/overview.md"
        - Messages:
          - Request: "authorization/1.0/request.md"
          - Response: "authorization/1.0/response.md"
    - Proofs:
        - Overview: "proofs/overview.md"
        - Messages (1.0):
          - Contract invoke request: "proofs/1.0/contract-invoke-request.md"
          - Request: "proofs/1.0/request.md"
          - Response: "proofs/1.0/response.md"
    - Revocation:
        - Overview: "revocation/overview.md"
        - Messages (1.0):
          - Request status: "revocation/1.0/request-status.md"
          - Status: "revocation/1.0/status.md"
    - Report Problem:
        - Overview: "report-problem/overview.md"
        - Messages:
            - Report Problem: "report-problem/2.0/report-problem-message.md"
    - Discovery:
        - Overview: "discovery/overview.md"
        - Messages:
            - Discovery Queries: "discovery/2.0/discovery.md"
  - Standard Proposals:
      - JWZ: "proposals/jwz/overview.md"

plugins:
  - search
  - mermaid2
copyright: powered by DIDComm

extra:
  analytics:
    provider: custom
    property: GTM-5TKTB44
