site_name: Iden3 documentation

site_url: https://iden3.io/
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep purple
  logo: logo-white.svg
  # favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
    - content.code.copy
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - fenced_code

nav:
  - Home: "index.md"
  - W3C credential:
    - Refresh service: "w3c/refresh-service/overview.md"
    - Credential Statuses: "w3c/status/overview.md"
    - Display method: "w3c/display-method/overview.md"
  - Protocol:  
    - Credentials:
        - Overview: "protocol/credentials/overview.md"
        - Messages:
          - Issuance Request: "protocol/credentials/1.0/issuance-request.md"
          - Issuance Response: "protocol/credentials/1.0/issuance-response.md"
          - Fetch Request: "protocol/credentials/1.0/fetch-request.md"
          - Offer: "protocol/credentials/1.0/offer.md"
          - Status update: "protocol/credentials/1.0/status-update.md"
          - Refresh: "protocol/credentials/1.0/refresh.md"
    - Authorization:
        - Overview: "protocol/authorization/overview.md"
        - Messages:
          - Request: "protocol/authorization/1.0/request.md"
          - Response: "protocol/authorization/1.0/response.md"
    - Proofs:
        - Overview: "protocol/proofs/overview.md"
        - Messages:
          - Contract invoke request: "protocol/proofs/1.0/contract-invoke-request.md"
          - Request: "protocol/proofs/1.0/request.md"
          - Response: "protocol/proofs/1.0/response.md"
    - Revocation:
        - Overview: "protocol/revocation/overview.md"
        - Messages:
          - Request status: "protocol/revocation/1.0/request-status.md"
          - Status: "protocol/revocation/1.0/status.md"

plugins:
  - search
  - mermaid2

extra:
  analytics:
    provider: custom
    property: GTM-5TKTB44
